Medic_App/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Medic_App import views as medic_views
from django.contrib.auth import views as auth_views
from Medic_App import forms

urlpatterns = [
    url(r'^$', medic_views.home, name='home'),
    url(r'^admin$', medic_views.admin, name='admin'),
    url(r'^admin/symptom$', medic_views.admin_symptom, name='admin_symptom'),
    url(r'^admin/disease$', medic_views.admin_disease, name='admin_disease'),    
    url(r'^info$', medic_views.info, name='info'),
    url(r'^check-up$', medic_views.checkup, name='check-up'),
    url(r'^medic_chat$', medic_views.medicchat, name='medic_chat'),
    url(r'^patients_chat$', medic_views.patientschat, name='patients_chat'),
    url(r'^login$', auth_views.login, {'template_name':'login.html', 'authentication_form': forms.LoginForm}, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': '/medic'}, name='logout'),
    url(r'^register$', medic_views.register, name='register'),
    url(r'^confirm-registration/(?P<username>\w+)/(?P<token>[a-z0-9\-]+)$',
        medic_views.confirm_registration, name='confirm'),
    url(r'^confirm-doctor/(?P<username>\w+)$',
        medic_views.confirm_doctor, name='confirm_doctor'),
    url(r'^confirm-patient/(?P<username>\w+)$',
        medic_views.confirm_patient, name='confirm_patient'),
    url(r'^find_username$', medic_views.find_username, name='find_username'),
    url(r'^find_password$', medic_views.find_password, name='find_password'),
    url(r'^add_symptom$', medic_views.add_symptom, name='add_symptom'),
    url(r'^add_disease$', medic_views.add_disease, name='add_disease'),
    url(r'^add_symptom_type$', medic_views.add_symptom_type, name='add_symptom_type'),
    url(r'^add_symptom_detail$', medic_views.add_symptom_detail, name='add_symptom_detail'),
    url(r'^delete_symptom_type/(?P<pk>\d+)$', medic_views.delete_symptom_type, name='delete_symptom_type'),
    url(r'^delete_symptom_detail/(?P<pk>\d+)$', medic_views.delete_symptom_detail, name='delete_symptom_detail'),
    url(r'^modify_symptom_type/(?P<pk>\d+)$', medic_views.modify_symptom_type, name='modify_symptom_type'),
    url(r'^modify_symptom_detail/(?P<pk>\d+)$', medic_views.modify_symptom_detail, name='modify_symptom_detail'),
    url(r'^get_detail_list$', medic_views.get_detail_list, name='get_detail_list'),
    url(r'^delete_disease/(?P<pk>\d+)$', medic_views.delete_disease, name='delete_disease'),
    url(r'^get_checked_up$$', medic_views.get_checked_up, name='get_checked_up'),
    url(r'^add_patients_chat$', medic_views.add_patients_chat, name='add_patients_chat'),
    url(r'^join_chat$', medic_views.join_chat, name="join_chat"),
    url(r'^send_msg$', medic_views.send_msg, name="send_msg"),
    url(r'^get_msg$', medic_views.get_msg, name="get_msg"),
    url(r'^add_medic_chat$', medic_views.add_medic_chat, name='add_medic_chat'),
]

Medic_Project/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

Medic_App/models.py
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.

status_choices = (
	("0", "need-confirmation"),
	("1", "patient"),
	("2", "doctor"),
)

class Status(models.Model):
	user = models.ForeignKey(User)
	status = models.CharField(max_length=30, choices=status_choices)

class SymptomType(models.Model):
	name = models.CharField(max_length=50)
	added_by = models.ForeignKey(User)

class Symptom(models.Model):
	name = models.CharField(max_length=100)
	symptomType = models.ForeignKey(SymptomType)
	added_by = models.ForeignKey(User)

commonness_choices = (
	("1", "very uncommon"),
	("2", "uncommon"),
	("3", "common"),
	("4", "very common"),
)

class Disease(models.Model):
	name = models.CharField(max_length=50)
	symptoms = models.ManyToManyField(Symptom)
	commonness = models.CharField(max_length=1, choices=commonness_choices)
	added_by = models.ForeignKey(User)

type_choices = (
	("1", "medic chat"),
	("2", "patients chat"),
)

class ChatRoom(models.Model):
	name = models.CharField(max_length=100)
	participants = models.ManyToManyField(User)
	type = models.CharField(max_length=20, choices=type_choices)

class Message(models.Model):
	sent = models.ForeignKey(User)
	room = models.ForeignKey(ChatRoom)
	content = models.CharField(max_length=500)

Medic_App/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from django.core.validators import validate_email
from models import *

MAX_UPLOAD_SIZE = 2500000

# modified from class notes
class RegistrationForm(forms.Form):
    username = forms.CharField(max_length = 30,
		    widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    firstname = forms.CharField(max_length = 30,
	    widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    lastname = forms.CharField(max_length = 30,
	    widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))
    email = forms.CharField(max_length = 40, validators = [validate_email],
            widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'E-mail'}))
    password1 = forms.CharField(max_length = 200, 
                                label='Password', 
                                widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2 = forms.CharField(max_length = 200, 
                                label='Confirm password',  
                                widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))

    def clean_password2(self):
	password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords did not match.")
        return password2

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__exact=username):
            raise forms.ValidationError("Username is already taken.")
        return username

    def clean_email(self):
	email = self.cleaned_data.get('email')
	if User.objects.filter(email__exact=email):
	    raise forms.ValidationError("Email is already in use.")
        return email

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control', 'placeholder':'Password'}))

Medic_App/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db import transaction
from django.core.mail import send_mail, EmailMessage
from django.contrib.auth.tokens import default_token_generator
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, Http404
import random
import string
import json
from collections import Counter

from Medic_App.forms import *

# Create your views here.

def home(request):
	return render(request, 'index.html', {})

@login_required
def admin(request):
	if not request.user.is_authenticated() or not request.user.email == "medic.email.service@gmail.com":
    		raise Http404
	users = Status.objects.all()
	return render(request, 'admin.html', {'list': users})

@login_required
def admin_symptom(request):
	if not request.user.is_authenticated() or not request.user.email == "medic.email.service@gmail.com":
    		raise Http404
	type = SymptomType.objects.all()
	detail = Symptom.objects.all()
	return render(request, 'admin_symptom.html', {'type': type, 'detail': detail})

@login_required
def admin_disease(request):
	if not request.user.is_authenticated() or not request.user.email == "medic.email.service@gmail.com":
    		raise Http404
	disease = Disease.objects.all()
	return render(request, 'admin_disease.html', {'disease': disease})

def info(request):
	return render(request, 'info.html', {})

def checkup(request):
    symptomTypeList = SymptomType.objects.order_by('name')
    return render(request, 'check-up.html', {'symptomTypeList':symptomTypeList})

@login_required
def medicchat(request):
	chatList = ChatRoom.objects.filter(type="medic")
	return render(request, 'medic_chat.html', {'chatList': chatList})

@login_required
def patientschat(request):
	chatList = ChatRoom.objects.filter(type="patients")
	return render(request, 'patients_chat.html', {'chatList': chatList})

@transaction.atomic
def register(request):
    context = {}

    if request.method == 'GET':
        context['form'] = RegistrationForm()
        return render(request, 'register.html', context)

    form = RegistrationForm(request.POST)
    context['form'] = form

    if not form.is_valid():
        return render(request, 'register.html', context)
    if not 'status' in request.POST or not request.POST['status']:
	return render(request, 'register.html', context)
    if request.POST['status'] == 'doctor' and (len(request.FILES) != 2):
	return render(request, 'register.html', context)

    new_user = User.objects.create_user(username=form.cleaned_data['username'], 
                                        password=form.cleaned_data['password1'],
					email=form.cleaned_data['email'],
					first_name=form.cleaned_data['firstname'],
					last_name=form.cleaned_data['lastname'])
    new_user.is_active = False
    new_user.save()

    token = default_token_generator.make_token(new_user)

    email_body = """
Please click the link below to verify your email address and complete the registration:
http://%s%s

If you registered as medical doctor, it may take a few days until the administrator confirms your proof to practice medicine.
""" % (request.get_host(), 
       reverse('confirm', args=(new_user.username, token)))

    send_mail(subject="Verify your email address",
              message= email_body,
              from_email="medic.email.service@gmail.com",
              recipient_list=[new_user.email])

    context['email'] = form.cleaned_data['email']

    if (request.POST['status'] == 'doctor') :
	    status = 'need-confirmation'
    else:
	    status = 'patient'

    new_status = Status(user=new_user, status=status)
    new_status.save()

    if status == 'need-confirmation':
	admin_email_body = """
Username: %s
First Name: %s
Last Name: %s
email: %s
confirmation link: http://%s%s
declination link: http://%s%s
""" % (new_user.username, new_user.first_name, new_user.last_name, new_user.email,
       request.get_host(), reverse('confirm_doctor', kwargs={'username':new_user.username}),
       request.get_host(), reverse('confirm_patient', kwargs={'username':new_user.username}))
        admin_notify = EmailMessage(subject="New user doctor confirmation", body=admin_email_body,
			from_email="medic.email.service@gmail.com", to=["medic.email.service@gmail.com"])
	file1 = request.FILES['file1']
	file2 = request.FILES['file2']
	admin_notify.attach(file1.name, file1.read(), file1.content_type)
	admin_notify.attach(file2.name, file2.read(), file2.content_type)
	admin_notify.send()

    return render(request, 'needs-confirmation.html', context)

@transaction.atomic
def confirm_registration(request, username, token):
    user = get_object_or_404(User, username=username)

    if not default_token_generator.check_token(user, token):
        raise Http404

    user.is_active = True
    user.save()
    return render(request, 'confirmed.html', {})
    
@login_required
@transaction.atomic
def confirm_doctor(request, username):
    if not request.user.is_authenticated() or not request.user.email == "medic.email.service@gmail.com":
    	raise Http404

    user = get_object_or_404(User, username=username)
    user_status = get_object_or_404(Status, user=user)

    user_status.status = 'doctor'
    user_status.save()
    return redirect(reverse('admin'))

@login_required
@transaction.atomic
def confirm_patient(request, username):
    if not request.user.is_authenticated() or not request.user.email == "medic.email.service@gmail.com":
    	raise Http404

    user = get_object_or_404(User, username=username)
    user_status = get_object_or_404(Status, user=user)

    user_status.status = 'patient'
    user_status.save()
    return redirect(reverse('admin'))

def find_username(request):
    context = {}

    if request.method == 'GET':
        return render(request, 'find_username.html', context)

    firstname = request.POST['firstname']
    lastname = request.POST['lastname']
    email = request.POST['email']

    try:
        user = User.objects.get(email=email)
    except ObjectDoesNotExist:
	return render(request, 'find_username.html', {'error': 'No user matches the information.'})
    if (user.first_name != firstname or user.last_name != lastname) :
        return render(request, 'find_username.html', {'error': 'No user matches the information.'})

    email_body = """
Your username is
%s
""" % (user.username)

    send_mail(subject="Your username",
              message= email_body,
              from_email="medic.email.service@gmail.com",
              recipient_list=[email])

    context['email'] = email

    return render(request, 'needs-confirmation.html', context)

@transaction.atomic
def find_password(request):
    context = {}

    if request.method == 'GET':
        return render(request, 'find_password.html', context)

    username = request.POST['username']
    email = request.POST['email']

    try:
        user = User.objects.get(username=username)
    except ObjectDoesNotExist:
	return render(request, 'find_password.html', {'error': 'No user matches the information.'})
    if (user.email != email) :
        return render(request, 'find_password.html', {'error': 'No user matches the information.'})

    new_password = ''.join(random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range(10))

    email_body = """
Your new password is
%s
""" % (new_password)

    send_mail(subject="Your password",
              message= email_body,
              from_email="medic.email.service@gmail.com",
              recipient_list=[email])

    user.set_password(new_password)
    user.save()
    context['email'] = email

    return render(request, 'needs-confirmation.html', context)

@login_required
def add_symptom(request):
    if not request.user.is_authenticated():
        return render(request, 'not_doc.html', {})
    user_status = get_object_or_404(Status, user=request.user)
    if user_status.status == "patient":
        return render(request, 'not_doc.html', {})
    if user_status.status == "need-confirmation":
        return render(request, 'not_confirmed_doc.html', {})
    if user_status.status != "doctor":
	return Http404

    symptomTypeList = SymptomType.objects.order_by('name')
    return render(request, 'add_symptom.html', {'symptomTypeList': symptomTypeList})

@login_required
@transaction.atomic
def add_symptom_type(request):
    if not request.user.is_authenticated():
        return render(request, 'not_doc.html', {})
    user_status = get_object_or_404(Status, user=request.user)
    if user_status.status == "patient":
        return render(request, 'not_doc.html', {})
    if user_status.status == "need-confirmation":
        return render(request, 'not_confirmed_doc.html', {})
    if user_status.status != "doctor":
	return Http404

    symptomTypeList = SymptomType.objects.all()
    if not 'symptom_type' in request.POST or not request.POST['symptom_type']:
        return render(request, 'add_symptom.html', {'errortype': 'Please enter a valid symptom type.',
		'symptomTypeList': symptomTypeList})

    try:
        type = SymptomType.objects.get(name=request.POST['symptom_type'])
	return render(request, 'add_symptom.html', {'errortype': 'The symptom type you entered already exists in the database.',
		'symptomTypeList': symptomTypeList})
    except ObjectDoesNotExist:
	type = SymptomType(name=request.POST['symptom_type'], added_by=request.user)
	type.save()
	return render(request, 'updated.html', {})

@login_required
@transaction.atomic
def add_symptom_detail(request):
    if not request.user.is_authenticated():
        return render(request, 'not_doc.html', {})
    user_status = get_object_or_404(Status, user=request.user)
    if user_status.status == "patient":
        return render(request, 'not_doc.html', {})
    if user_status.status == "need-confirmation":
        return render(request, 'not_confirmed_doc.html', {})

Medic_App/templates/add_disease.html
{% extends "base.html" %}

{% block title %}
Add New Disease
{% endblock %}

{% block js_files %}
{% load staticfiles %}
<script src="{% static 'js/check-up.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
<form method="post" action="{% url 'add_disease'%}">
<div class="form-center">
<h2>Add New Disease</h2>
<input class="form-control" type="text" name="name" placeholder="New Disease Name" maxlength="50">
{% if error_name %}
<p class="error">
{{error_name}}
</p>
{% endif %}
<select name="commonness" class="form-control">
	<option value="">Select Commonness</option>
	<option value="1">Very Uncommon</option>
	<option value="2">Uncommon</option>
	<option value="3">Common</option>
	<option value="4">Very Common</option>
</select>
{% if error_common %}
<p class="error">
{{error_common}}
</p>
{% endif %}
</div>
<div class="row" style="margin-bottom:40px;">
  <div class="col-md-4">
    <h2>1. Symptom Type</h2>
	<div class="selection_list" id="symptom_type_list">
	{% for type in symptomTypeList %}
	<div class="selection_elem" id="type_elem_{{type.pk}}" onclick="select_type({{type.pk}})">
	{{type.name}}
	</div>
	{% endfor %}
	</div>
  </div>
  <div class="col-md-4">
    <h2>2. Symptom Detail</h2>
	<div class="selection_list" id="symptom_detail_list">
		<div class="default_elem">
		Please Select a Symptom Type.
		</div>
	</div>
  </div>
  <div class="col-md-4">
    <h2>3. Disease Symptoms</h2>
	<div class="selection_list" id="your_list">
		<div class="default_elem">
		Please Select a Symptom Detail.
		</div>
	</div>
  </div>
</div>
{% if error_select %}
<p class="error" style="text-align: center; margin-top: -30px;">
{{error_select}}
</p>
{% endif %}
<div id="hidden_checkboxes">
</div>
<div class="bottom-text form-center">
{% csrf_token %}
    <input class="btn btn-lg btn-default btn-block bottom-text" type="submit" value="Add New Disease">
</div>
</form>
{% endblock %}

Medic_App/templates/add_patients_chat.html
{% extends "base.html" %}

{% block title %}
Add New Patients Chat
{% endblock %}

{% block content %}
<form class="form-center" method="post" action="{% url 'add_patients_chat'%}">
<h2>Add New Chat Room</h2>
<input class="form-control" type="text" name="chat_name" placeholder="New Chat Room" maxlength="100">
{% if error %}
<p class="error">
{{error}}
</p>
{% endif %}
{% csrf_token %}
<input class="btn btn-lg btn-default btn-block bottom-text" type="submit" value="Add">
</form>
{% endblock %}

Medic_App/templates/add_symptom.html
{% extends "base.html" %}

{% block title %}
Add New Symptom
{% endblock %}

{% block content %}
<form class="form-center" method="post" action="{% url 'add_symptom_type'%}">
<h2>Add New Symptom Type</h2>
<input class="form-control" type="text" name="symptom_type" placeholder="New Symptom Type" maxlength="50">
{% if errortype %}
<p class="error">
{{errortype}}
</p>
{% endif %}
{% csrf_token %}
<input class="btn btn-lg btn-default btn-block bottom-text" type="submit" value="Add">
</form>
{% endblock %}

{% block logo-block %}
<div class="info-block">
<div class="container">
<form class="form-center" method="post" action="{% url 'add_symptom_detail'%}">
<h2>Add New Symptom Detail</h2>
<select name="symptom_type" class="form-control">
  <option value="">Select Symptom Type</option>
  {% for type in symptomTypeList %}
  <option value="{{type.pk}}">{{type.name}}</option>
  {% endfor %}
</select>

<input class="form-control" type="text" name="symptom_detail" placeholder="New Symptom Detail" maxlength="100">
{% if errordetail %}
<p class="error">
{{errordetail}}
</p>
{% endif %}
{% csrf_token %}
<input class="btn btn-lg btn-info btn-block bottom-text" type="submit" value="Add">
</form>
</div>
</div>
{% endblock %}

Medic_App/templates/admin_disease.html
{% extends "admin_base.html" %}

{% block content %}
<br />
Disease
<table>
<tr>
<td>Name</td>
<td>Commonness</td>
<td>Symptoms</td>
<td>Added by</td>
<td>Change</td>
</tr>
{% for d in disease %}
<tr>
<td>{{d.name}}</td>
<td>{{d.get_commonness_display}}</td>
<td>{% for s in d.symptoms.all %}
{{s.symptomType.name}}: {{s.name}}<br />
{% endfor %}
</td>
<td>{{d.added_by.username}}</td>
<td><a href="{% url 'delete_disease' d.pk %}">Delete</a></td>
</tr>
{% endfor %}
</table>

{% endblock %}

Medic_App/templates/base.html
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %} {% endblock %}</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/medic.css' %}">
</head>

<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
	  <a class="navbar-brand" href="{% url 'home' %}">
        <img class="medic-logo" alt="logo" src="{% static "img/logo.png" %}">
      </a>
    </div>
	
	<div class="collapse navbar-collapse">
	  <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'info' %}"><p class="navbar-text">Info</p></a></li>
		<li><a href="{% url 'check-up' %}"><p class="navbar-text">Check-up</p></a></li>
		<li><a href="{% url 'medic_chat' %}"><p class="navbar-text">Medic Chat</p></a></li>
		<li><a href="{% url 'patients_chat' %}"><p class="navbar-text">Patients Chat</p></a></li>
		{% if user.is_authenticated %}
		<li><p class="navbar-text">{{user}}</p></a></li>
		<li><a href="{% url 'logout' %}"><button type="button" class="btn btn-primary navbar-btn" >Sign out</button></a></li>
		{% else %}
	    <li><a href="{% url 'login' %}"><button type="button" class="btn btn-primary navbar-btn" >Sign in</button></a></li>
		{% endif %}
	  </ul>
	</div>
  </div>
</nav>
  
<div class="container">
  {% block content %}
  {% endblock %}
</div>

{% block logo-block %}
{% endblock %}

{% block js_files %}
{% endblock %}
</body>
</html>

Medic_App/templates/confirmed.html
{% extends "base.html" %}

{% block title %}
Confirmation
{% endblock %}

{% block content %}
<h1>Email Confirmed!</h1>
<h4 class="bottom-text">Please sign in to fully access Medic.</h4>
{% endblock %}

Medic_App/templates/find_username.html
{% extends "base.html" %}

{% block title %}
Find Username
{% endblock %}

{% block content %}
<form class="form-center" method="post" action="{% url 'find_username'%}">

<h2>Find username</h2>
<input class="form-control" type="text" name="firstname" placeholder="First Name" maxlength="30">
<input class="form-control" type="text" name="lastname" placeholder="Last Name" maxlength="30">
<input class="form-control" type="text" name="email" placeholder="Email Address" maxlength="40">
{% if error %}
<p class="error">
{{error}}
</p>
{% endif %}
{% csrf_token %}
<input class="btn btn-lg btn-default btn-block bottom-text" type="submit" value="Send email">
</form>
{% endblock %}

Medic_App/templates/needs-confirmation.html
{% extends "base.html" %}

{% block title %}
Confirmation
{% endblock %}

{% block content %}
<h1>Email Confirmation Has Been Sent to</h1>
<h4 class="bottom-text">{{email}}</h4>
{% endblock %}

Medic_App/templates/new_chat_added.html
{% extends "base.html" %}

{% block title %}
Added
{% endblock %}

{% block content %}
<h1>New Chat Room Added Successfully</h1>
<h4 class="bottom-text">Administrator may monitor your chat room.</h4>
{% endblock %}

Medic_App/templates/no_chat.html
{% extends "base.html" %}

{% block title %}
Patients Chat
{% endblock %}

{% block content %}
<h1>No Chat Selected...</h1>
<h4 class="bottom-text">You must select a chat room to enter.</h4>
{% endblock %}

Medic_App/templates/no_select.html
{% extends "base.html" %}

{% block title %}
Check-up
{% endblock %}

{% block content %}
<h1>Need More Information...</h1>
<h4 class="bottom-text">You must select at least one symptom to use this feature.</h4>
{% endblock %}

Medic_App/templates/not_confirmed_doc.html
{% extends "base.html" %}

{% block title %}
Blocked
{% endblock %}

{% block content %}
<h1>Please Come Back Later!</h1>
<h4 class="bottom-text">It may take a few days to confirm a medical doctor.</h4>
{% endblock %}

Medic_App/templates/not_doc.html
{% extends "base.html" %}

{% block title %}
Blocked
{% endblock %}

{% block content %}
<h1>Sorry... Not Available</h1>
<h4 class="bottom-text">This service is only available to registered medical doctors.</h4>
{% endblock %}

Medic_App/templates/updated.html
{% extends "base.html" %}

{% block title %}
Updated
{% endblock %}

{% block content %}
<h1>Successfully Updated Database</h1>
<h4 class="bottom-text">Thank you for your contribution.</h4>
{% endblock %}